[workspace]
resolver = "3"
members = [
  "crates/assets",
  "crates/comet",
  "crates/icons",
  "crates/ui",
  "crates/workspace",
]

[workspace.package]
version = "0.0.0"
license = "AGPL-3.0-or-later"
authors = ["Mayank Verma <errmayank@gmail.com>"]
edition = "2024"
publish = false

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.dependencies]
################### External crates ###################
anyhow = { version = "1.0" }
core-text = { version = "=21.0.0" }                          # https://github.com/zed-industries/zed/issues/47168
gpui = { git = "https://github.com/zed-industries/zed" }
rust-embed = { version = "8.0", features = ["debug-embed"] }
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.15" }
strum = { version = "0.27", features = ["derive"] }
############### Workspace member crates ###############
assets = { path = "crates/assets" }
icons = { path = "crates/icons" }
ui = { path = "crates/ui" }
workspace = { path = "crates/workspace" }
