[workspace]
resolver = "3"
members = [
  "crates/assets",
  "crates/comet",
  "crates/component",
  "crates/editor",
  "crates/http_client",
  "crates/icons",
  "crates/input",
  "crates/reqwest_client",
  "crates/settings",
  "crates/settings_macros",
  "crates/theme",
  "crates/ui",
  "crates/ui_macros",
  "crates/util",
  "crates/workspace",
]

[workspace.package]
version = "0.0.0"
license = "AGPL-3.0-or-later"
authors = ["Mayank Verma <errmayank@gmail.com>"]
edition = "2024"
publish = false

[workspace.lints.clippy]
type_complexity = { level = "allow" }
style = { level = "allow" }

[workspace.dependencies]
##################################################
# External crates
##################################################
anyhow = { version = "1.0" }
bytes = { version = "1.11" }
core-text = { version = "=21.0.0" } # https://github.com/zed-industries/zed/issues/47168
dirs = { version = "6.0" }
futures = { version = "0.3" }
gpui = { git = "https://github.com/zed-industries/zed", package = "gpui" }
http = { version = "1.4" }
http-body = { version = "1.0" }
inventory = { version = "0.3.21" }
palette = { version = "0.7.5", default-features = false, features = ["std"] }
parking_lot = { version = "0.12.1" }
pretty_assertions = { version = "1.4" }
quote = { version = "1.0.44" }
reqwest = { version = "0.13", default-features = false, features = [
  "charset",
  "http2",
  "multipart",
  "rustls",
  "socks",
  "stream",
  "system-proxy",
] }
rust-embed = { version = "8.0", features = ["debug-embed"] }
schemars = { version = "1.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
smallvec = { version = "1.15" }
strum = { version = "0.27", features = ["derive"] }
syn = { version = "2.0.114", features = ["extra-traits", "full", "visit-mut"] }
text = { git = "https://github.com/zed-industries/zed", package = "text" }
tokio = { version = "1.49", features = ["rt", "rt-multi-thread"] }
unicode-segmentation = { version = "1.12" }
url = { version = "2.5" }
uuid = { version = "1.1.2", features = ["v4"] }
##################################################
# Workspace member crates
##################################################
assets = { path = "crates/assets" }
component = { path = "crates/component" }
editor = { path = "crates/editor" }
http_client = { path = "crates/http_client" }
icons = { path = "crates/icons" }
input = { path = "crates/input" }
reqwest_client = { path = "crates/reqwest_client" }
settings = { path = "crates/settings" }
settings_macros = { path = "crates/settings_macros" }
theme = { path = "crates/theme" }
ui = { path = "crates/ui" }
ui_macros = { path = "crates/ui_macros" }
util = { path = "crates/util" }
workspace = { path = "crates/workspace" }
