[workspace]
resolver = "3"
members = ["crates/comet", "crates/workspace"]

[workspace.package]
version = "0.0.0"
license = "AGPL-3.0-or-later"
authors = ["Mayank Verma <errmayank@gmail.com>"]
edition = "2024"
publish = false

[workspace.dependencies]
################### External crates ###################
core-text = { version = "=21.0.0" } # https://github.com/zed-industries/zed/issues/47168
gpui = { git = "https://github.com/zed-industries/zed" }
############### Workspace member crates ###############
workspace = { path = "crates/workspace" }
