[workspace]
resolver = "3"
members = ["crates/comet"]

[workspace.package]
version = "0.0.0"
license = "AGPL-3.0-or-later"
authors = ["Mayank Verma <errmayank@gmail.com>"]
edition = "2024"
publish = false

[workspace.dependencies]
core-text = { version = "=21.0.0" }
gpui = { git = "https://github.com/zed-industries/zed" }
