[package]
name = "input"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "input"
path = "src/input.rs"

[dependencies]
gpui = { workspace = true }
ui = { workspace = true }
