[package]
name = "zaku"
description = "Fast, open-source API client with fangs."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
assets = { workspace = true }
editor = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
menu = { workspace = true }
settings = { workspace = true }
theme = { workspace = true }
workspace = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-text = { workspace = true }
