[package]
name = "zaku"
description = "Fast, open-source API client with fangs."
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["mimalloc"]
mimalloc = ["dep:mimalloc"]

[dependencies]
assets = { workspace = true }
editor = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
gpui_platform = { workspace = true, features = [
  "font-kit",
  "screen-capture",
  "wayland",
  "x11",
] }
menu = { workspace = true }
mimalloc = { workspace = true, optional = true }
settings = { workspace = true }
theme = { workspace = true }
workspace = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-text = { workspace = true }
