[package]
name = "reqwest_client"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "reqwest_client"
path = "src/reqwest_client.rs"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http_client = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
