[package]
name = "settings"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "settings"
path = "src/settings.rs"

[features]
test-support = []

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
notify = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
settings_macros = { workspace = true }
util = { workspace = true }
