[package]
name = "editor"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "editor"
path = "src/editor.rs"

[dependencies]
gpui = { workspace = true }
input = { workspace = true }
text = { workspace = true }
unicode-segmentation = { workspace = true }
