[package]
name = "workspace"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "workspace"
path = "src/workspace.rs"

[dependencies]
gpui = { workspace = true }
http_client = { workspace = true }
input = { workspace = true }
reqwest_client = { workspace = true }
ui = { workspace = true }
