[package]
name = "workspace"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
name = "workspace"
path = "src/workspace.rs"

[dependencies]
editor = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
http_client = { workspace = true }
input = { workspace = true }
menu = { workspace = true }
reqwest_client = { workspace = true }
theme = { workspace = true }
ui = { workspace = true }
